name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: 'rajeev.sharma@nagarro.com'
          password: 'Raju@!ndia'
      # Build Angular app image
      - name: Build and push Angular UI
        uses: docker/build-push-action@v5
        with:
          context: ./usersApp
          file: ./usersApp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/poc-app-ui:v1

      # Build Node API image
      - name: Build and push Node API
        uses: docker/build-push-action@v5
        with:
          context: ./usersAPI
          file: ./usersAPI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/poc-api-service:v1   
